const data = [
  {
    id: 1,
    title: "The Effective Engineer",
    author: ["Edmond Lau"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2009,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/the-effective-engineer.png",
    status: "Available",
  },
  {
    id: 2,
    title: "Built To Last",
    author: ["Jim Collins", "Jerry I. Porras"],
    genre: ["Business", "Entrepreneurship"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2001,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/built-to-last.png",
    status: "Borrowed Out",
  },
  {
    id: 3,
    title: "The Lean Startup",
    author: ["Eric Reis"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2005,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/the-lean-startup.png",
    status: "Available",
  },
  {
    id: 4,
    title: "Effective Python",
    author: ["Diomidis Spinellis"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: null,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/effective-python.png",
    status: "Available",
  },
  {
    id: 5,
    title: "Big Magic",
    author: ["Elizabeth Gilbert"],
    genre: ["Business", "Entrepreneurship"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2014,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/big-magic.png",
    status: "Available",
  },
];

const allBooks = [
  {
    id: 1,
    title: "The Effective Engineer",
    author: ["Edmond Lau"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2009,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/the-effective-engineer.png",
    status: "Available",
  },
  {
    id: 2,
    title: "Built To Last",
    author: ["Jim Collins", "Jerry I. Porras"],
    genre: ["Business", "Entrepreneurship"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2001,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/built-to-last.png",
    status: "Borrowed Out",
  },
  {
    id: 3,
    title: "The Lean Startup",
    author: ["Eric Reis"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2005,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/the-lean-startup.png",
    status: "Available",
  },
  {
    id: 4,
    title: "Effective Python",
    author: ["Diomidis Spinellis"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: null,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/effective-python.png",
    status: "Available",
  },
  {
    id: 5,
    title: "Big Magic",
    author: ["Elizabeth Gilbert"],
    genre: ["Business", "Entrepreneurship"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2014,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/big-magic.png",
    status: "Available",
  },
  {
    id: 6,
    title: "Big Magic",
    author: ["Elizabeth Gilbert"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2014,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/effective-python.png",
    status: "Available",
  },
  {
    id: 7,
    title: "The Effective Engineer",
    author: ["Edmond Lau"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2009,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/the-effective-engineer.png",
    status: "Available",
  },
  {
    id: 8,
    title: "Built To Last",
    author: ["Jim Collins", "Jerry I. Porras"],
    genre: ["Business", "Entrepreneurship"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2001,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/built-to-last.png",
    status: "Borrowed Out",
  },
  {
    id: 9,
    title: "The Lean Startup",
    author: ["Eric Reis"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2005,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/the-lean-startup.png",
    status: "Available",
  },
  {
    id: 10,
    title: "Effective Python",
    author: ["Diomidis Spinellis"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: null,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/effective-python.png",
    status: "Available",
  },
  {
    id: 11,
    title: "Big Magic",
    author: ["Elizabeth Gilbert"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2014,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/big-magic.png",
    status: "Available",
  },
  {
    id: 12,
    title: "Big Magic",
    author: ["Elizabeth Gilbert"],
    genre: ["Business", "Entrepreneurship"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2014,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/the-effective-engineer.png",
    status: "Available",
  },
  {
    id: 13,
    title: "The Lean Startup",
    author: ["Eric Reis"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2005,
    labels: ["Creative", "Self-help"],
    image: "../assets/books/the-lean-startup.png",
    status: "Available",
  },
];

const searchResultsData = [
  "Four Steps To The Epiphany Revised - James McEnroe",
  "Four Steps To The Epiphany - James McEnroe",
  "The Lean Start Up - Eric Reiss",
  "No Excuses - Brian Tracy",
  "Harry Potter and the Goblet of Fire - J.K Rowlings",
  "Song of Fire and Ice - George R.R Martin",
];
