const data = [
  {
    id: 1,
    title: "Built To Last",
    author: ["Jim Collins", "Jerry I. Porras"],
    genre: ["Business", "Entrepreneurship"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2001,
    image: "../assets/books/built-to-last.png",
    status: "Borrowed Out",
  },
  {
    id: 2,
    title: "Effective Python",
    author: ["Diomidis Spinellis"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: null,
    image: "../assets/books/effective-python.png",
    status: "Available",
  },
  {
    id: 3,
    title: "Big Magic",
    author: ["Elizabeth Gilbert"],
    genre: ["Business", "Entrepreneurship"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2014,
    image: "../assets/books/big-magic.png",
    status: "Available",
  },
  {
    id: 4,
    title: "The Effective Engineer",
    author: ["Edmond Lau"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2009,
    image: "../assets/books/the-effective-engineer.png",
    status: "Available",
  },
  {
    id: 5,
    title: "The Lean Startup",
    author: ["Eric Reis"],
    genre: ["Motivational"],
    rating: 4.0,
    likes: 29,
    people: 31,
    date_publushed: 2005,
    image: "../assets/books/the-lean-startup.png",
    status: "Available",
  },
];

export default data;
